version: '3.7'

services:
    currency-exchange-service:
        image: currency-exchange-service:latest
        mem_limit: 700m
        ports:
        - 8000:8000
        networks:
        - currency-network
        depends_on:
        - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411

    currency-conversion-service:
        image: currency-conversion-service:latest
        mem_limit: 700m
        ports:
        - 8100:8100
        networks:
        - currency-network
        depends_on:
        - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411

    api-gateway:
        image: api-gateway:latest
        mem_limit: 700m
        ports:
            - 8765:8765
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411

    naming-server:
        image: nameing-service:latest
        mem_limit: 700m
        ports:
        - 8761:8761
        networks:
        - currency-network

    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 700m
        ports:
        - 9411:9411
        networks:
        - currency-network

networks:
    currency-network: